
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Privacy Policy - CampaignStudio",
    description: "Read the Privacy Policy for CampaignStudio Digital Media Pvt. Ltd.",
}

export default function PrivacyPage() {
    return (
        <div className="container px-4 md:px-6 mx-auto py-20 max-w-4xl">
            <h1 className="text-4xl md:text-5xl font-bold mb-8 tracking-tight">Privacy Policy</h1>
            <p className="text-muted-foreground mb-12">Last updated: December 2025</p>

            <div className="space-y-12 text-foreground/90 leading-relaxed text-lg">
                <p className="mb-4">
                    This privacy policy (&quot;Policy&quot;) describes how CampaignStudio Digital Media Pvt. Ltd. or any of its subsidiaries or affiliates (&quot;We&quot;, &quot;Us&quot;, &quot;Our&quot;) handles the processing of Personal Data collected from You.
                </p>

                <section>
                    <h2 className="text-2xl font-bold mb-4">1. Definitions</h2>
                    <ul className="space-y-4">
                        <li><strong>1.1 &quot;Controller&quot;</strong> is the person, authority, agency, or entity that alone or with others, decides the purposes and methods of processing Personal Data.</li>
                        <li><strong>1.2 &quot;End-User&quot;</strong> refers to anyone with whom the Subscriber interacts using the Services.</li>
                        <li><strong>1.3 &quot;Personal Data&quot;</strong> means any information related to an identified or identifiable individual, including identifiers like names, IDs, location data, or characteristics unique to their identity.</li>
                        <li><strong>1.4 &quot;Usage Data&quot;</strong> is automatically gathered data generated by the Services or its infrastructure (e.g., page visit duration).</li>
                        <li><strong>1.5 &quot;Process&quot;</strong> refers to any activity performed on Personal Data, such as collection, storage, or deletion, with or without automated tools.</li>
                        <li><strong>1.6 &quot;Processor&quot;</strong> is the person, authority, or entity that handles Personal Data on behalf of the Controller.</li>
                        <li><strong>1.7 &quot;Services&quot;</strong> is defined in the <a href="/terms" className="text-primary hover:underline">Terms of Service</a>.</li>
                        <li><strong>1.8 &quot;Subscriber&quot;</strong> is the person or organization that subscribes to the Services by accepting the Terms of Service.</li>
                        <li><strong>1.9 &quot;Terms of Service&quot;</strong> is the binding agreement between You and Us, outlining the rules for using the Services, accessible at <a href="/terms" className="text-primary hover:underline">campaignstudio.in/terms</a>.</li>
                        <li><strong>1.10 &quot;Website(s)&quot;</strong> refers to any site operated by Us.</li>
                        <li><strong>1.11 &quot;You&quot; and &quot;Your&quot;</strong> refers to any identified or identifiable individual whose Personal Data we process as the Controller.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">2. Personal Data We Collect</h2>
                    <p className="mb-4"><strong>2.1</strong> Most of the Personal Data we collect comes directly from You, such as:</p>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>(a) when You subscribe to our Services, we collect your name, email, phone number, address, etc.;</li>
                        <li>(b) when You submit forms on our Website(s) or participate in features like surveys, events, or customer support;</li>
                        <li>(c) when You provide testimonials or authorize Us to connect with a third-party service that shares relevant data with Us.</li>
                    </ul>
                    <p className="mb-4"><strong>2.2</strong> We may also collect Personal Data indirectly, for example:</p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>(a) from authorized third parties like marketing lists or social media;</li>
                        <li>(b) automatically when You use the Services, gathering data like IP address, browser type, time on each page, and more;</li>
                        <li>(c) via cookies and tracking on our Websites;</li>
                        <li>(d) from your device type or unique identifiers when accessed through a mobile device;</li>
                        <li>(e) from business or channel partners through whom You create or access an account.</li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">3. Purpose of Processing Personal Data</h2>
                    <p>
                        <strong>3.1</strong> We process Your Personal Data to facilitate access, complete transactions, provide support, communicate updates, improve services, conduct promotions, investigate potential security issues, and personalize Your experience.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">4. Sharing of Personal Data</h2>
                    <p>
                        <strong>4.1</strong> We may share Your data with affiliates and third-party service providers for delivering Services, processing transactions, preventing fraud, and marketing in compliance with applicable laws.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">5. International Transfers</h2>
                    <p>
                        <strong>5.1</strong> While we process data primarily within the USA, transfers to other regions may occur, ensuring adequate data protection measures as per applicable laws.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">6. Data Retention</h2>
                    <p>
                        <strong>6.1</strong> We retain Personal Data as needed for legitimate business purposes, deleting or securely storing data when no longer required.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">7. Security Measures</h2>
                    <p>
                        <strong>7.1</strong> We use security measures suited to protect Your Personal Data based on risk. Contact Us if You have any security concerns.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">8. Your Rights</h2>
                    <p>
                        <strong>8.1</strong> You have rights to access, update, delete, object to, or restrict processing of Your Personal Data. For marketing, You can opt out anytime, and You may file complaints to data protection authorities if necessary.
                    </p>
                </section>

                <section>
                    <h2 className="text-2xl font-bold mb-4">9. Privacy of Children</h2>
                    <p>
                        <strong>9.1</strong> We do not collect data from children under 18. Parents aware of data provided by minors should contact us for assistance.
                    </p>
                </section>

                <div className="mt-8 border-t pt-8">
                    <p className="font-semibold">CampaignStudio Digital Media Pvt. Ltd.</p>
                    <p>GST No. 07AAHCC4303J1ZU</p>
                    <p>J1/15A, Khirki Extension, Panchsheel Extension</p>
                    <p>Malviya Nagar, New Delhi-110017</p>
                    <p className="mt-2">Contact: <a href="mailto:connect@campaignstudio.in" className="text-primary hover:underline">connect@campaignstudio.in</a></p>
                </div>
            </div>
        </div>
    )
}
